package com.appyhigh.newsfeedsdk.apiclient

object Endpoints {

    const val GET_ICONS_NOTIFICATION = "get-icons-notification"
    const val GET_ICONS_SEARCH = "get-icons-search"
    const val USER_ACTION_NOTIFICATION = "user-action-notification"
    const val USER_ACTION_SEARCH = "user-action-search"


    const val GET_INTERESTS_ENCRYPTED = "/api/v4/get-interests"
    const val UPDATE_USER_ENCRYPTED = "/api/v4/update-user"
    const val GET_LANGUAGES_ENCRYPTED = "/api/v4/get-languages"
    const val USER_DETAILS_ENCRYPTED = "/api/v4/user-details"
    const val GET_INTERESTS_APPWISE_ENCRYPTED = "/api/v4/get-interests-appwise"
    const val GET_FEEDS_ENCRYPTED = "/api/v4/get-feeds"
    const val POST_IMPRESSIONS_ENCRYPTED = "/api/v4/post-impressions"
    const val COMMENT_POST_ENCRYPTED = "/api/v4/comment-post"
    const val GET_CRICKET_SCHEDULE_ENCRYPTED = "/api/v4/get-cricket-schedule-m"
    const val GET_CRICKET_TABS_ENCRYPTED = "/api/v4/get-cricket-tabs"
    const val GET_CRYPTO_HOME_ENCRYPTED = "/api/v4/get-crypto-home"
    const val GET_CRYPTO_DETAILS_ENCRYPTED = "/api/v4/get-crypto-details"
    const val GET_CRYPTO_COIN_DETAILS_ENCRYPTED = "/api/v4/get-coin-details"
    const val CRYPTO_ALERT_VIEW_ENCRYPTED = "/api/v4/crypto-alert-view"
    const val CRYPTO_ALERT_ADD_ENCRYPTED = "/api/v4/crypto-alert-add"
    const val CRYPTO_ALERT_MODIFY_ENCRYPTED = "/api/v4/crypto-alert-modify"
    const val CRYPTO_ALERT_DELETE_ENCRYPTED = "/api/v4/crypto-alert-delete"
    const val CRYPTO_SEARCH_ENCRYPTED = "/api/v4/crypto-search"
    const val GET_CRYPTO_COIN_LIST_ENCRYPTED = "/api/v4/crypto-currency-converter"
    const val EXPLORE_ENCRYPTED = "/api/v4/explore"
    const val FOLLOW_PUBLISHER_ENCRYPTED = "/api/v4/follow-publisher"
    const val GET_POSTS_DETAILS_ENCRYPTED = "/api/v4/get-posts-details"
    const val GET_POSTS_BY_TAG_ENCRYPTED = "/api/v4/get-posts-by-tag"
    const val PODCAST_HOME_ENCRYPTED = "/api/v4/podcast-home"
    const val PODCAST_CATEGORY_ENCRYPTED = "/api/v4/podcast-category"
    const val PODCAST_PUBLISHER_ENCRYPTED = "/api/v4/podcast-publisher"
    const val GET_PUBLISHER_POSTS_ENCRYPTED = "/api/v4/get-publisher-posts"
    const val REACT_POST_ENCRYPTED = "/api/v4/react-post"
    const val REPORT_ISSUES_ENCRYPTED = "/api/v4/report-issues"
    const val REPORT_POST_ENCRYPTED = "/api/v4/report-post"
    const val CHECK_EMAIL_NUMBER_AVAILABILITY_ENCRYPTED = "/api/v4/check-email-number-availability"
    const val GET_REGIONAL_FEEDS_ENCRYPTED = "/api/v4/get-regional-feeds"
    const val GET_STATE_LIST_ENCRYPTED = "/api/v4/get-states-names"
    const val GET_CONFIG_ENCRYPTED = "/api/v4/config"
    const val BLOCK_PUBLISHER = "/api/v4/block-publisher"
    const val GET_BLOCK_PUBLISHER_DETAILS = "/api/v4/get-block-publisher-details"
    const val GET_SINGLE_POST = "/api/v4/app-lock-get-single-post"
    const val GET_MULTIPLE_POSTS = "/api/v4/app-lock-get-multiple-posts"
}